name: SuperLinter

on: push

jobs:
  super-lint:
    name: Start Linting Code
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run SuperLinter
        uses: github/super-linter@v3
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
